version: 0.2

phases:
  install:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-north-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t q6:latest .
      - docker tag q6 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/q6:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/q6:latest
cache:
  paths:
    - /var/lib/docker/**/*
