version: 0.2

phases:
  install:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-north-1)
  build:
    commands:
      - echo Build started on `date`
      - /bin/sh -c python3.6 -m pip install pip --upgrade
      - echo Building the Docker image...          
      - docker build -t q6:latest .
      - docker tag q6 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/q6:latest      
  post_build:
    commands:
      - echo Test docker run
      - docker run -d q6:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/q6:latest
cache:
  paths:
    - /var/lib/docker/**/*
